id: AF14ABE37
base_file: f2331.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:09:48.485936
  last_modified_at: 2022-05-30 23:09:48.485948
