id: AF14ABE37
base_file: fFC0B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:09:48.489631
  last_modified_at: 2022-05-30 23:09:48.489636
